### PR TITLE
Fixes non-termination on zero width attribute.

### LINKED ISSUE #8: Infinite loop in adoc-kwf-attriblist
Function adoc-kwf-attriblist can enter an infinite loop leading to a hung emacs process.

Original report and test case: https://stackoverflow.com/questions/21787592/debugging-emacs-freezing-in-adoc-mode

### LINKED ISSUE #9: broken syntax [,] causes emacs to hang
The string `[,]` appears to cause adoc-mode to hang. The syntax `[source,lang]` is used to allow syntax highlighting of code blocks. Another user may incorrectly leave out the `lang`. If this happens adoc-mode will hang indefinitely parsing the file. 

adoc-mode version: 20130917.0

Reproduction steps:
1. create an ascii-doc document or switch to adoc mode in an existing buffer.
2. type the characters `[,]`

Observed behavior: 
Emacs hangs. This is sometimes recoverable by repeatedly hitting `C-g` and backspace to delete the string.

### PR DESCRIPTION
**Pull request by fidergo-stephane-gourichon**
@sensorflo on issue #8 and #9 you mentioned "I now just pushed version 0.6.3 which contains the fix for this bug, based on the work of phillord." 

I see in history commit e6b8e6984360b69ba3e05012f04723fe91fe81db by @phillord but it's very different from commit 767596ecf01a6843bd2d5410e3a3cfde8f0d8170 which AFAIK actually fixes the problem.

Furthermore release 0.6.3 appears nowhere today (2016-02-22) in [project history](https://github.com/sensorflo/adoc-mode/releases) up to 168ffa3f8efc3a635cc8f9422b7117a3a99af804 and @twlz0ne mentions on #9 that bug still occurs.

I can't find version 20151119.914 mentioned by @twlz0ne.

Can you check if this very pull request makes sense?

Thank you for your attention.
(Auto-generated pull request text below.)

----

Previously, this would greedily hang on the text "[,]" because
as text-property-not-all was assumed incorrectly to always return
greater than point if it returned at all. In this case, we just
advance to end.

Closes #8
Closes #9

### CODE REVIEW

**Comment by twlz0ne** [comment]
http://melpa.org/#/adoc-mode

**Comment by twlz0ne** [comment]
My fault, 20151119.914 is the melap package version, adoc-mode version is 0.6.4: https://melpa.org/packages/adoc-mode-20151119.914.el

**Comment by sensorflo** [comment]
Commit e6b8e69 also fixes the problem, but IMHO in a more direct and nice way than the original 767596e by phillord. 

I am confused. Is this bug now really still a problem for anybody, or is all well and it was just a mistake by twlz0one, see his comment in this thread before this comment here.

**Comment by sensorflo** [comment]
After discussing with fidergo-stephane-gourichon also in the comments on commit e6b8e69, neither 767596e nor this pull request here is needed. The bug is fixed by e6b8e69. For the record: when I wrote e6b8e69 I took the initial idea from phillord's 767596e, but the two commits look rather different.

**Pull request closed without merging**
